### PR TITLE
Agent can get_bytes_received and get_bytes_sent

### PR DESCRIPTION
**Pull request by sax**
I don't see a good way to connect two agents together in the tests, but it would be nice to see values greater than 0.

### CODE REVIEW

**Comment by k0nserv** [comment]
> I don't see a good way to connect two agents together in the tests, but it would be nice to see values greater than 0.

There are tests in `agent_test.rs` that use `Vnet` construct to entirely abstract away the real network and have two agents talk to each other that way. You could also construct an `Agent` that has a `AgentConn` where the `selected_pair` contains mocked `Candidates` that don't actually send and test it that way.

That said, these new changes are trivial and the tests aren't super important. I'd rather see a test for `AgentConn`'s method that assert that the values reported are correct after calling `recv` and `send` on it.

**Comment by sax** [comment]
@k0nserv what do you think about this update to the pull request? In some ways it's a duplication of the test in `agent_transport_test.rs`, so I was thinking of adding assertions there... this version seems less surprising, though.

**Comment by k0nserv** [comment]
Looks good!

**Comment by sax** [comment]
:heart: thank you for all the feedback!

**Pull request merged**
